### ISSUE TITLE
batch treats same query with different request variables as a duplicate

### ISSUE THREAD

**Issue by lerhaupt** [relay-tools/react-relay-network-modern#31]
https://github.com/relay-tools/react-relay-network-modern/blob/331a2f7a317d7070da870764eb2baed9b897c401/src/middlewares/batch.js#L139

I have a refetch query in modern that is being run on two instances of the same component, each with different variables on the request.  Within the batch middleware, the relayReqId is identical and the same name as the refetch query.  However, the fetch variables are different, but any subsequent request in the same batch that has different variables seems to only get treated as a dup and not fetched.

**Comment by nodkz** [comment]
Confirm the bug!

For backward compatibility **needs to write a new middleware with name `batch2`**. Logic should be changed by using arrays (the assumption that for batched request server returns responses in the same order) instead of Maps (where are responses linked with requests via `payload.id`).

### In the `passThroughBatch` method
https://github.com/relay-tools/react-relay-network-modern/blob/331a2f7a317d7070da870764eb2baed9b897c401/src/middlewares/batch.js#L110-L143
- `relayReqId` should be removed
- `requestMap` renamed to `requestList` and used `push` method
- `duplicates` logic should be removed for simplicity (and may be added in future). Also should be removed in line https://github.com/relay-tools/react-relay-network-modern/blob/331a2f7a317d7070da870764eb2baed9b897c401/src/middlewares/batch.js#L172

### In `sendRequests` method 
- should be changed `ids` on array order
- `payload.id` should be removed and also should be rewritten on array order https://github.com/relay-tools/react-relay-network-modern/blob/331a2f7a317d7070da870764eb2baed9b897c401/src/middlewares/batch.js#L198-L205

--------

In my apps I do not use batching (all requests sending in parallel - page loads more progressive and feels more alive). So I'm not redy to write a new `batch` middleware. But with pleasure review and merge PR if somebody make it. Help wanted!

**Comment by codecvlt** [comment]
+1

Any chance this will be fixed soon? This middleware is largely unusable because of this issue.

I use <QueryRenderer> with the same graphql fragment to render multiple configurations of the same widget on the same page. All widgets receive the same data which is bad.

**Comment by nodkz** [comment]
If somebody sends Pull Request with fix I'll merge it.

Sorry, I haven't bandwidth for this issue to do it myself.

**Comment by joelvh** [comment]
@nodkz this is implemented in #66

**Comment by joelvh** [comment]
@nodkz can this be closed based on #66 ?

**Comment by nodkz** [comment]
Sure!
